server:
  port: 5000
  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    #url: jdbc:mysql://aahewdkwpqx2bc.cpsjlkklldoy.us-east-1.rds.amazonaws.com:3306/ebdb
    url: jdbc:mysql://aahewdkwpqx2bc.cpsjlkklldoy.us-east-1.rds.amazonaws.com:3306/ebdb
    username: sungjin
    password: tlqkfsha02
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #테이블의 이름을 설정(naming)
      use-new-id-generator-mappings: false #jpa가 사용하는 기본넘버링전전략을 따라가지 않는다는 뜻
    show-sql: true #콘솔에 SQL문을 한줄로 뜨게함
    properties:
      hibernate.format_sql: true #콘솔에 출력되는 SQL문을 정렬시켜서 출력
      

  jackson:
    serialization:
      fail-on-empty-beans: false